export const ProductFileFormat: { key: string; title: string; format: string }[] = [
  { key: 'GLB', title: 'GLB', format: '.glb' },
  { key: 'GLTF', title: 'GLTF', format: '.gltf' },
  { key: 'USDZ', title: 'USDZ', format: '.usdz' },
  { key: 'FBX', title: 'FBX', format: '.fbx' },
  { key: 'OBJ', title: 'OBJ', format: '.obj' },
  { key: 'STL', title: ' Stereolithography', format: '.stl' },
  { key: 'PLY', title: 'PLY', format: '.ply' },
  { key: 'DAE', title: 'Collada', format: '.dae' },
  { key: 'LWO', title: ' LightWave', format: '.lwo' },
  { key: 'LXO', title: ' Modo', format: '.lxo' },
  { key: 'MA', title: ' Maya', format: '.ma' },
  { key: 'MB', title: ' Maya', format: '.mb' },
  { key: 'BLEND', title: 'Blender', format: '.blend' },
  { key: 'C4D', title: 'Cinema 4D', format: '.c4d' },
  { key: 'MAX', title: '3ds Max', format: '.max' },
  { key: '3DS', title: '3ds Max', format: '.3ds' },
  { key: 'SPP', title: 'SPP', format: '.spp' },
  { key: 'GOZ', title: 'GOZ', format: '.goz' },
  { key: 'SKP', title: ' SketchUp', format: '.skp' },
  { key: 'UNITY', title: ' Unity', format: '.unitypackage' },
  { key: 'UASSET', title: ' Unreal', format: '.uasset' },
];
