/** @type {import('next').NextConfig} */

const withPlugins = require('next-compose-plugins');

const withEnv = { publicRuntimeConfig: { DEPLOY_ENV: process.env.DEPLOY_ENV } };
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
});

const withRewrites = {
  async rewrites() {
    return [
      //ENGLISH
      { source: '/en', destination: '/' },
      { source: '/en/blog', destination: '/blog' },
      { source: '/en/blog/:path', destination: '/blog/:path' },
      { source: '/en/blog/edit/:path', destination: '/blog/edit/:path' },
      { source: '/en/blog/:path1/:path2', destination: '/blog/:path1/:path2' },
      { source: '/en/explore', destination: '/explore' },
      { source: '/en/explore/:path', destination: '/explore/:path' },
      { source: '/en/sale-off/:path', destination: '/sale-off/:path' },
      { source: '/en/product/:path', destination: '/product/:path' },
      { source: '/en/modeling', destination: '/modeling' },
      { source: '/en/modeling/orders/:path', destination: '/modeling/orders/:path' },
      { source: '/en/modeling/orders', destination: '/modeling/orders' },
      { source: '/en/notification', destination: '/notification' },
      { source: '/en/login', destination: '/login' },
      { source: '/en/register', destination: '/register' },
      { source: '/en/change-email', destination: '/change-email' },
      { source: '/en/forgot-password', destination: '/forgot-password' },
      { source: '/en/reset-password', destination: '/reset-password' },
      { source: '/en/user', destination: '/user' },
      { source: '/en/user/:path', destination: '/user/:path' },
      { source: '/en/user/my-orders/:path', destination: '/user/my-orders/:path' },
      { source: '/en/user/my-orders/detail/:path', destination: '/user/my-orders/detail/:path' },
      { source: '/en/user/models/:path', destination: '/user/models/:path' },
      { source: '/en/user/settings/:path', destination: '/user/settings/:path' },
      { source: '/en/seller/:path', destination: '/seller/:path' },
      { source: '/en/showroom/:path', destination: '/showroom/:path' },
      {
        source: '/en/showroom/dashboard/setting/:path',
        destination: '/showroom/dashboard/setting/:path',
      },
      { source: '/en/seller/product/:path', destination: '/seller/product/:path' },
      { source: '/en/seller/orders/:path', destination: '/seller/orders/:path' },
      { source: '/en/contact-us', destination: '/contact-us' },
      { source: '/en/help-center', destination: '/help-center' },
      { source: '/en/help-center/:path', destination: '/help-center/:path' },
      { source: '/en/upload-model', destination: '/upload-model' },
      { source: '/en/upload-model/:path', destination: '/upload-model/:path' },
      { source: '/en/withdraw', destination: '/withdraw' },
      { source: '/en/cart', destination: '/cart' },
      { source: '/en/checkout', destination: '/checkout' },
      { source: '/en/verify', destination: '/verify' },
      { source: '/en/license/:path', destination: '/license/:path' },
      { source: '/en/free-models/:path', destination: '/free-models/:path' },
      //Showroom
      { source: '/en/showroom', destination: '/showroom' },
      { source: '/en/showroom/top-review', destination: '/showroom/top-review' },
      { source: '/en/showroom/top-view', destination: '/showroom/top-view' },
      { source: '/en/showroom/top-sold', destination: '/showroom/top-sold' },
      { source: '/en/showroom/dashboard/:path', destination: '/showroom/dashboard/:path' },
      {
        source: '/en/showroom/dashboard/showroom-card/:path',
        destination: '/showroom/dashboard/showroom-card/:path',
      },
      {
        source: '/en/showroom/:path1/products/:path2',
        destination: '/showroom/:path1/products/:path2',
      },
      {
        source: '/en/showroom/dashboard/orders/:path',
        destination: '/showroom/dashboard/orders/:path',
      },

      { source: '/en/dashboard', destination: '/dashboard' },
      { source: '/en/dashboard/models', destination: '/dashboard/models' },
      { source: '/en/dashboard/orders', destination: '/dashboard/orders' },
      { source: '/en/dashboard/orders/:path', destination: '/dashboard/orders/:path' },
      { source: '/en/dashboard/withdraw', destination: '/dashboard/withdraw' },
      { source: '/en/dashboard/reviews', destination: '/dashboard/reviews' },
      { source: '/en/dashboard/showroom/theme', destination: '/dashboard/showroom/theme' },
      {
        source: '/en/dashboard/showroom/theme/:path',
        destination: '/dashboard/showroom/theme/:path',
      },
      {
        source: '/en/dashboard/showroom/theme/preview/:path',
        destination: '/dashboard/showroom/theme/preview/:path',
      },
      { source: '/en/dashboard/showroom/card', destination: '/dashboard/showroom/card' },
      { source: '/en/dashboard/showroom/category', destination: '/dashboard/showroom/category' },
      { source: '/en/dashboard/setting', destination: '/dashboard/setting' },
      {
        source: '/en/showroom/:path1/products',
        destination: '/showroom/:path1/products',
      },

      //JAPAN
      { source: '/jp', destination: '/' },
      { source: '/jp/blog', destination: '/blog' },
      { source: '/jp/blog/:path', destination: '/blog/:path' },
      { source: '/jp/blog/:path1/:path2', destination: '/blog/:path1/:path2' },
      { source: '/jp/blog/edit/:path', destination: '/blog/edit/:path' },
      { source: '/jp/explore', destination: '/explore' },
      { source: '/jp/explore/:path', destination: '/explore/:path' },
      { source: '/jp/sale-off/:path', destination: '/sale-off/:path' },
      { source: '/jp/product/:path', destination: '/product/:path' },
      { source: '/jp/modeling', destination: '/modeling' },
      { source: '/jp/modeling/orders', destination: '/modeling/orders' },
      { source: '/jp/modeling/orders/:path', destination: '/modeling/orders/:path' },
      { source: '/jp/modeling/orders', destination: '/modeling/orders' },
      { source: '/jp/notification', destination: '/notification' },
      { source: '/jp/login', destination: '/login' },
      { source: '/jp/register', destination: '/register' },
      { source: '/jp/change-email', destination: '/change-email' },
      { source: '/jp/forgot-password', destination: '/forgot-password' },
      { source: '/jp/reset-password', destination: '/reset-password' },
      { source: '/jp/user', destination: '/user' },
      { source: '/jp/user/:path', destination: '/user/:path' },
      { source: '/jp/user/my-orders/:path', destination: '/user/my-orders/:path' },
      { source: '/jp/user/my-orders/detail/:path', destination: '/user/my-orders/detail/:path' },
      { source: '/jp/user/models/:path', destination: '/user/models/:path' },
      { source: '/jp/user/settings/:path', destination: '/user/settings/:path' },
      { source: '/jp/seller/:path', destination: '/seller/:path' },
      { source: '/jp/seller/product/:path', destination: '/seller/product/:path' },
      { source: '/jp/seller/orders/:path', destination: '/seller/orders/:path' },
      { source: '/jp/showroom/:path', destination: '/showroom/:path' },
      {
        source: '/jp/showroom/:path1/products/:path2',
        destination: '/showroom/:path1/products/:path2',
      },
      {
        source: '/jp/showroom/:path1/products',
        destination: '/showroom/:path1/products',
      },
      {
        source: '/jp/showroom/dashboard/setting/:path',
        destination: '/showroom/dashboard/setting/:path',
      },
      { source: '/jp/contact-us', destination: '/contact-us' },
      { source: '/jp/help-center', destination: '/help-center' },
      { source: '/jp/help-center/:path', destination: '/help-center/:path' },
      { source: '/jp/upload-model', destination: '/upload-model' },
      { source: '/jp/upload-model/:path', destination: '/upload-model/:path' },
      { source: '/jp/withdraw', destination: '/withdraw' },
      { source: '/jp/cart', destination: '/cart' },
      { source: '/jp/checkout', destination: '/checkout' },
      { source: '/jp/verify', destination: '/verify' },
      { source: '/jp/license/:path', destination: '/license/:path' },
      { source: '/jp/free-models/:path', destination: '/free-models/:path' },
      //Showroom
      { source: '/jp/showroom', destination: '/showroom' },
      { source: '/jp/showroom/top-review', destination: '/showroom/top-review' },
      { source: '/jp/showroom/top-view', destination: '/showroom/top-view' },
      { source: '/jp/showroom/top-sold', destination: '/showroom/top-sold' },
      { source: '/jp/showroom/dashboard/:path', destination: '/showroom/dashboard/:path' },
      {
        source: '/jp/showroom/dashboard/showroom-card/:path',
        destination: '/showroom/dashboard/showroom-card/:path',
      },
      {
        source: '/jp/showroom/:path1/products/:path2',
        destination: '/showroom/:path1/products/:path2',
      },
      {
        source: '/jp/showroom/dashboard/orders/:path',
        destination: '/showroom/dashboard/orders/:path',
      },

      { source: '/jp/dashboard', destination: '/dashboard' },
      { source: '/jp/dashboard/models', destination: '/dashboard/models' },
      { source: '/jp/dashboard/orders', destination: '/dashboard/orders' },
      { source: '/jp/dashboard/orders/:path', destination: '/dashboard/orders/:path' },
      { source: '/jp/dashboard/withdraw', destination: '/dashboard/withdraw' },
      { source: '/jp/dashboard/reviews', destination: '/dashboard/reviews' },
      { source: '/jp/dashboard/showroom/theme', destination: '/dashboard/showroom/theme' },
      {
        source: '/jp/dashboard/showroom/theme/:path',
        destination: '/dashboard/showroom/theme/:path',
      },
      {
        source: '/jp/dashboard/showroom/theme/preview/:path',
        destination: '/dashboard/showroom/theme/preview/:path',
      },
      { source: '/jp/dashboard/showroom/card', destination: '/dashboard/showroom/card' },
      { source: '/jp/dashboard/showroom/category', destination: '/dashboard/showroom/category' },
      { source: '/jp/dashboard/setting', destination: '/dashboard/setting' },
      {
        source: '/jp/showroom/:path1/products',
        destination: '/showroom/:path1/products',
      },

      //KOREAN
      { source: '/kr', destination: '/' },
      { source: '/kr/blog', destination: '/blog' },
      { source: '/kr/blog/:path', destination: '/blog/:path' },
      { source: '/kr/blog/:path1/:path2', destination: '/blog/:path1/:path2' },
      { source: '/kr/blog/edit/:path', destination: '/blog/edit/:path' },
      { source: '/kr/explore', destination: '/explore' },
      { source: '/kr/explore/:path', destination: '/explore/:path' },
      { source: '/kr/sale-off/:path', destination: '/sale-off/:path' },
      { source: '/kr/product/:path', destination: '/product/:path' },
      { source: '/kr/modeling', destination: '/modeling' },
      { source: '/kr/modeling/orders', destination: '/modeling/orders' },
      { source: '/kr/modeling/orders/:path', destination: '/modeling/orders/:path' },
      { source: '/kr/modeling/orders', destination: '/modeling/orders' },
      { source: '/kr/notification', destination: '/notification' },
      { source: '/kr/login', destination: '/login' },
      { source: '/kr/register', destination: '/register' },
      { source: '/kr/change-email', destination: '/change-email' },
      { source: '/kr/forgot-password', destination: '/forgot-password' },
      { source: '/kr/reset-password', destination: '/reset-password' },
      { source: '/kr/user', destination: '/user' },
      { source: '/kr/user/:path', destination: '/user/:path' },
      { source: '/kr/user/my-orders/:path', destination: '/user/my-orders/:path' },
      { source: '/kr/user/my-orders/detail/:path', destination: '/user/my-orders/detail/:path' },
      { source: '/kr/user/models/:path', destination: '/user/models/:path' },
      { source: '/kr/user/settings/:path', destination: '/user/settings/:path' },
      {
        source: '/kr/showroom/:path1/products/:path2',
        destination: '/showroom/:path1/products/:path2',
      },
      {
        source: '/kr/showroom/:path1/products',
        destination: '/showroom/:path1/products',
      },
      {
        source: '/kr/showroom/dashboard/setting/:path',
        destination: '/showroom/dashboard/setting/:path',
      },
      { source: '/kr/seller/:path', destination: '/seller/:path' },
      { source: '/kr/seller/product/:path', destination: '/seller/product/:path' },
      { source: '/kr/seller/orders/:path', destination: '/seller/orders/:path' },
      { source: '/kr/showroom/:path', destination: '/showroom/:path' },
      { source: '/kr/contact-us', destination: '/contact-us' },
      { source: '/kr/help-center', destination: '/help-center' },
      { source: '/kr/help-center/:path', destination: '/help-center/:path' },
      { source: '/kr/upload-model', destination: '/upload-model' },
      { source: '/kr/upload-model/:path', destination: '/upload-model/:path' },
      { source: '/kr/withdraw', destination: '/withdraw' },
      { source: '/kr/cart', destination: '/cart' },
      { source: '/kr/checkout', destination: '/checkout' },
      { source: '/kr/verify', destination: '/verify' },
      { source: '/kr/license/:path', destination: '/license/:path' },
      { source: '/kr/free-models/:path', destination: '/free-models/:path' },
      //Showroom
      { source: '/kr/showroom', destination: '/showroom' },
      { source: '/kr/showroom/top-review', destination: '/showroom/top-review' },
      { source: '/kr/showroom/top-view', destination: '/showroom/top-view' },
      { source: '/kr/showroom/top-sold', destination: '/showroom/top-sold' },
      { source: '/kr/showroom/dashboard/:path', destination: '/showroom/dashboard/:path' },
      {
        source: '/kr/showroom/dashboard/showroom-card/:path',
        destination: '/showroom/dashboard/showroom-card/:path',
      },
      {
        source: '/kr/showroom/:path1/products/:path2',
        destination: '/showroom/:path1/products/:path2',
      },
      {
        source: '/kr/showroom/dashboard/orders/:path',
        destination: '/showroom/dashboard/orders/:path',
      },
      { source: '/kr/dashboard', destination: '/dashboard' },
      { source: '/kr/dashboard/models', destination: '/dashboard/models' },
      { source: '/kr/dashboard/orders', destination: '/dashboard/orders' },
      { source: '/kr/dashboard/orders/:path', destination: '/dashboard/orders/:path' },
      { source: '/kr/dashboard/withdraw', destination: '/dashboard/withdraw' },
      { source: '/kr/dashboard/reviews', destination: '/dashboard/reviews' },
      { source: '/kr/dashboard/showroom/theme', destination: '/dashboard/showroom/theme' },
      {
        source: '/kr/dashboard/showroom/theme/:path',
        destination: '/dashboard/showroom/theme/:path',
      },
      {
        source: '/kr/dashboard/showroom/theme/preview/:path',
        destination: '/dashboard/showroom/theme/preview/:path',
      },
      { source: '/kr/dashboard/showroom/card', destination: '/dashboard/showroom/card' },
      { source: '/kr/dashboard/showroom/category', destination: '/dashboard/showroom/category' },
      { source: '/kr/dashboard/setting', destination: '/dashboard/setting' },
      {
        source: '/kr/showroom/:path1/products',
        destination: '/showroom/:path1/products',
      },

      //VIETNAMESE
      { source: '/vn', destination: '/' },
      { source: '/vn/blog', destination: '/blog' },
      { source: '/vn/blog/:path', destination: '/blog/:path' },
      { source: '/vn/blog/:path1/:path2', destination: '/blog/:path1/:path2' },
      { source: '/vn/blog/edit/:path', destination: '/blog/edit/:path' },
      { source: '/vn/explore', destination: '/explore' },
      { source: '/vn/explore/:path', destination: '/explore/:path' },
      { source: '/vn/sale-off/:path', destination: '/sale-off/:path' },
      { source: '/vn/product/:path', destination: '/product/:path' },
      { source: '/vn/modeling', destination: '/modeling' },
      { source: '/vn/modeling/orders', destination: '/modeling/orders' },
      { source: '/vn/modeling/orders/:path', destination: '/modeling/orders/:path' },
      { source: '/vn/modeling/orders', destination: '/modeling/orders' },
      { source: '/vn/notification', destination: '/notification' },
      { source: '/vn/login', destination: '/login' },
      { source: '/vn/register', destination: '/register' },
      { source: '/vn/change-email', destination: '/change-email' },
      { source: '/vn/forgot-password', destination: '/forgot-password' },
      { source: '/vn/reset-password', destination: '/reset-password' },
      { source: '/vn/user', destination: '/user' },
      { source: '/vn/user/:path', destination: '/user/:path' },
      { source: '/vn/user/my-orders/:path', destination: '/user/my-orders/:path' },
      { source: '/vn/user/my-orders/detail/:path', destination: '/user/my-orders/detail/:path' },
      { source: '/vn/user/models/:path', destination: '/user/models/:path' },
      { source: '/vn/user/settings/:path', destination: '/user/settings/:path' },
      {
        source: '/vn/showroom/:path1/products/:path2',
        destination: '/showroom/:path1/products/:path2',
      },
      {
        source: '/vn/showroom/:path1/products',
        destination: '/showroom/:path1/products',
      },
      {
        source: '/vn/showroom/dashboard/setting/:path',
        destination: '/showroom/dashboard/setting/:path',
      },
      { source: '/vn/seller/:path', destination: '/seller/:path' },
      { source: '/vn/seller/product/:path', destination: '/seller/product/:path' },
      { source: '/vn/seller/orders/:path', destination: '/seller/orders/:path' },
      { source: '/vn/showroom/:path', destination: '/showroom/:path' },
      { source: '/vn/contact-us', destination: '/contact-us' },
      { source: '/vn/help-center', destination: '/help-center' },
      { source: '/vn/help-center/:path', destination: '/help-center/:path' },
      { source: '/vn/upload-model', destination: '/upload-model' },
      { source: '/vn/upload-model/:path', destination: '/upload-model/:path' },
      { source: '/vn/withdraw', destination: '/withdraw' },
      { source: '/vn/cart', destination: '/cart' },
      { source: '/vn/checkout', destination: '/checkout' },
      { source: '/vn/verify', destination: '/verify' },
      { source: '/vn/license/:path', destination: '/license/:path' },
      { source: '/vn/free-models/:path', destination: '/free-models/:path' },
      //Showroom
      { source: '/vn/showroom', destination: '/showroom' },
      { source: '/vn/showroom/top-review', destination: '/showroom/top-review' },
      { source: '/vn/showroom/top-view', destination: '/showroom/top-view' },
      { source: '/vn/showroom/top-sold', destination: '/showroom/top-sold' },
      { source: '/vn/showroom/dashboard/:path', destination: '/showroom/dashboard/:path' },
      {
        source: '/vn/showroom/dashboard/showroom-card/:path',
        destination: '/showroom/dashboard/showroom-card/:path',
      },
      {
        source: '/vn/showroom/:path1/products/:path2',
        destination: '/showroom/:path1/products/:path2',
      },
      {
        source: '/vn/showroom/dashboard/orders/:path',
        destination: '/showroom/dashboard/orders/:path',
      },
      { source: '/vn/dashboard', destination: '/dashboard' },
      { source: '/vn/dashboard/models', destination: '/dashboard/models' },
      { source: '/vn/dashboard/orders', destination: '/dashboard/orders' },
      { source: '/vn/dashboard/orders/:path', destination: '/dashboard/orders/:path' },
      { source: '/vn/dashboard/withdraw', destination: '/dashboard/withdraw' },
      { source: '/vn/dashboard/reviews', destination: '/dashboard/reviews' },
      { source: '/vn/dashboard/showroom/theme', destination: '/dashboard/showroom/theme' },
      {
        source: '/vn/dashboard/showroom/theme/:path',
        destination: '/dashboard/showroom/theme/:path',
      },
      {
        source: '/vn/dashboard/showroom/theme/preview/:path',
        destination: '/dashboard/showroom/theme/preview/:path',
      },
      { source: '/vn/dashboard/showroom/card', destination: '/dashboard/showroom/card' },
      { source: '/vn/dashboard/showroom/category', destination: '/dashboard/showroom/category' },
      { source: '/vn/dashboard/setting', destination: '/dashboard/setting' },
      {
        source: '/vn/showroom/:path1/products',
        destination: '/showroom/:path1/products',
      },
    ];
  },
};

const nextConfig = withPlugins([
  [withBundleAnalyzer],
  withEnv,
  withRewrites,
  {
    reactStrictMode: false,
    images: { domains: [] },
    compiler: { styledComponents: true },
  },
  {
    images: {
      remotePatterns: [
        {
          protocol: 'https',
          hostname: '**',
        },
      ],
    },
  },
  {
    i18n: {
      locales: ['detect', 'en', 'kr', 'jp', 'vn'],
      defaultLocale: 'detect',
      localeDetection: false,
    },
  },
]);

module.exports = nextConfig;
