export enum DashboardPageEnum {
  DASHBOARD = 'DASHBOARD',
  MODEL = 'MODEL',
  ORDER = 'ORDER',
  WITHDRAW = 'WITHDRAW',
  REVIEW = 'REVIEW',
  SHOWROOM = 'SHOWROOM',
  SHOWROOM_THEME = 'SHOWROOM_THEME',
  SHOWROOM_CARD = 'SHOWROOM_CARD',
  SHOWROOM_CATEGORY = 'SHOWROOM_CATEGORY',
  SETTING = 'SETTING',
}
export type DashboardPage = DashboardPageEnum;
